src/app/lego-hub/features/hub-properties-feature-factory.service.ts
src/app/lego-hub/features/hub-properties-feature.ts
src/app/lego-hub/features/io-feature.ts
src/app/lego-hub/hub-discovery.service.ts
src/app/lego-hub/hub-factory.service.ts
src/app/lego-hub/hub.ts
src/app/lego-hub/logging/hub-logger-factory.service.ts
src/app/lego-hub/logging/hub-logger.service.ts
src/app/lego-hub/logging/index.ts
src/app/lego-hub/messages/characteristic-data-stream-factory.service.ts
src/app/lego-hub/messages/outbound-messenger-factory.service.ts
src/app/lego-hub/messages/outbound-messenger.ts
src/app/lego-hub/provide-lego-hub-environment.ts
src/app/logging/console-logging.service.ts
src/app/logging/i-logger.ts
src/app/logging/index.ts
src/app/logging/logging.service.spec.ts
src/app/store/effects/hub-attached-ios-effects.ts
src/app/store/effects/hub-io-data.effects.ts
src/app/store/effects/hub-io-supported-modes-effects.service.ts
src/app/store/effects/hub-port-mode-info-effects.ts
src/app/store/effects/hubs.effects.ts
src/app/store/hub-storage.service.ts
src/assets/i18n/en.json
src/main.ts

hub api refactoring

---

angular.json
src/app/control-scheme/view/control-scheme-view/control-scheme-view.component.html
src/app/control-scheme/view/control-scheme-view/control-scheme-view.component.ts
src/app/lego-hub/constants.ts
src/app/lego-hub/features/io-feature.ts
src/app/lego-hub/hub-factory.service.ts
src/app/lego-hub/messages/hub-properties/hub-properties-reply-parser.service.ts
src/app/lego-hub/messages/inbound-message-listener.ts
src/app/lego-hub/messages/inbound-message.ts
src/app/store/actions/control-scheme-runner.actions.ts
src/app/store/actions/index.ts
src/app/store/effects/control-scheme-runner.effects.ts
src/app/store/effects/hub-attached-ios-effects.ts
src/app/store/effects/index.ts
src/app/store/i-state.ts
src/app/store/initial-state.ts
src/app/store/provide-store.ts
src/app/store/reducers/control-scheme-runner.reducers.ts
src/app/store/reducers/index.ts
src/app/store/selectors/control-scheme-runner.selectors.ts
src/app/store/selectors/hub-attached-io.selectors.ts
src/app/store/selectors/hub-io-supported-modes.selectors.ts
src/app/store/selectors/hubs.selectors.ts
src/app/store/selectors/index.ts
src/app/types/type-helpers.ts
src/main.ts

+ fix build warning
+ fix lint warnings

running control scheme initial

---

src/app/lego-hub/hub-factory.service.ts

we should start listening for attached IOs as early as possible. Also added minor connection error message

reorder hub api creation

---

src/app/control-schemes/control-scheme-list-item/control-scheme-list-item.component.html
src/app/control-schemes/control-scheme-list/control-scheme-list.component.html
src/app/control-schemes/control-scheme-list/control-scheme-list.component.scss
src/app/control-schemes/control-scheme-list/control-scheme-list.component.ts
src/app/control-schemes/view/control-scheme-view-io-list/control-scheme-view-io-list.component.html
src/app/control-schemes/view/control-scheme-view-io/control-scheme-view-io.component.html
src/app/control-schemes/view/control-scheme-view-io/control-scheme-view-io.component.ts
src/app/control-schemes/view/control-scheme-view/control-scheme-view.component.html
src/app/controllers/controllers-list/controllers-list-item/controllers-list-item.component.html
src/app/controllers/controllers-list/controllers-list/controllers-list.component.html
src/app/controllers/controllers-list/controllers-list/controllers-list.component.scss
src/app/hubs/hub-edit/hub-edit-form/hub-edit-form.component.ts
src/app/hubs/hubs-list/hubs-list/hubs-list.component.html
src/app/hubs/hubs-list/hubs-list/hubs-list.component.scss
src/app/hubs/hubs-list/hubs-list/hubs-list.component.ts
src/app/store/selectors/control-scheme.selectors.ts
src/assets/i18n/en.json

- add running scheme indicator to the list
- add icons to expansion panels
- add io type to io card at scheme view

multiple ui tweaks

---

src/app/control-schemes/edit/edit-form/control-scheme-output-form-factory.service.ts
src/app/lego-hub/constants.ts
src/app/lego-hub/features/motor-feature.ts
src/app/lego-hub/messages/port-operations/port-operations-outbound-message-factory.service.ts
src/app/tasks-processing/task-composer/composers/set-speed-composer.ts

lib: implement set motor absolute angle

---

src/app/lego-hub/features/hub-properties-feature.ts
src/app/lego-hub/features/io-feature.ts
src/app/lego-hub/features/motor-feature.ts
src/app/lego-hub/i-lego-hub-config.ts
src/app/lego-hub/messages/outbound-messenger-factory.service.ts
src/app/lego-hub/messages/outbound-messenger.ts
src/app/store/effects/hubs.effects.ts

- strict queue order implemented
- getPropertyValueWithRetries$ switched to new api
- messenger timeout and retries props moved to config

fix race in messenger

---

package-lock.json
package.json
src/app/control-schemes/control-scheme-list/control-scheme-list.component.html
src/app/control-schemes/edit/binding-output/control-scheme-binding-output.component.html
src/app/control-schemes/view/control-scheme-view/control-scheme-view.component.html
src/app/controllers/controllers-list/controllers-list/controllers-list.component.html
src/app/hubs/hubs-list/hubs-list/hubs-list.component.html
src/app/store/effects/hub-port-tasks.effects.ts
src/app/store/effects/hubs.effects.ts

+ remove ngrxPush in ngrxLet (bug of type inference in templates in webstorm has been fixed)

migrate to api v0.0.14

---

package-lock.json
package.json
src/app/store/actions/hub-attached-ios.actions.ts
src/app/store/actions/index.ts
src/app/store/effects/hub-attached-ios-effects.ts
src/app/store/effects/hub-io-supported-modes.effects.ts
src/app/store/i-state.ts
src/app/store/reducers/hub-attached-ios.reducers.ts
src/app/store/selectors/hub-io-supported-modes.selectors.ts
src/app/store/selectors/hub-port-mode-info.selectors.ts

...when an IO with POS and APOS capabilities are attached
+ bump api version

request and store encoder offsets

---

src/app/control-schemes/edit/binding-output/control-scheme-binding-output.component.scss
src/app/control-schemes/edit/edit-form/control-scheme-edit-form.component.html
src/app/control-schemes/edit/edit-form/control-scheme-edit-form.component.scss
src/app/control-schemes/edit/edit-form/control-scheme-edit-form.component.ts
src/app/main/nav-menu/nav-menu.component.html

- add badges to compact nav menu

fix control scheme edit width

---

src/app/store/controllers/controllers.reducer.ts
src/app/store/controllers/controllers.selectors.ts
src/app/store/controllers/gamepad-controller.effects.ts
src/app/store/controllers/keyboard-controller.effects.ts
src/app/store/provide-store.ts
src/app/store/selectors/controller-input-capture.selectors.ts

refactor: rewrite controller effects to functional effects

---

src/app/control-schemes/common/binding-edit/binding-servo/binding-servo-edit.component.ts
src/app/control-schemes/common/binding-edit/servo-calibration-dialog/servo-calibration.service.ts
src/app/store/effects/controllers/listen-connect/listen-gamepad-connect.effect.ts

+ gamepad connection detection, servo calibration final position

fix: servo binding edit position reading

---

src/app/control-schemes/common/binding-edit/binding-speed-shift/binding-speed-shift.component.ts
src/app/control-schemes/common/forms/builders/common-form-controls-builder.service.ts
src/app/control-schemes/common/forms/builders/speed-shift-binding-form-builder.service.ts
src/app/store/effects/tasks-processing/stop-scheme.effect.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/speed-shift-task-payload-factory.service.ts
src/assets/i18n/en.json

+ scheme stop w/o add/dec profile

fix: speed shift binding edit

---

src/app/control-schemes/common/binding-edit/servo-calibration-dialog/servo-calibration.service.ts
src/app/control-schemes/port-config-edit-page/port-config-edit-page.component.html
src/app/control-schemes/port-config-edit-page/port-config-edit-page.component.ts
src/app/shared/index.ts
src/app/shared/is-input-activated.ts
src/app/store/effects/controllers/capture-input/capture-gamepad-input.effect.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/angle-shift-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/set-angle-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/speed-shift-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/stepper-task-payload-factory.service.ts
src/app/store/selectors/controller-input.selectors.ts

+ increase gamepad polling interval
+ add validation messages to port config
+ fix float numbers in servo calibration results

fix: increase gamepad stick input activation level

---

src/app/control-schemes/common/binding-edit/binding-angle-shift/binding-angle-shift-edit.component.ts
src/app/control-schemes/common/binding-edit/binding-servo/binding-servo-edit.component.ts
src/app/control-schemes/control-scheme-page/port-command-task-summary/angle-shift-port-command-task-summary-builder.service.ts
src/app/control-schemes/control-scheme-page/port-command-task-summary/speed-shift-port-command-task-summary-builder.service.ts
src/assets/i18n/en.json
src/assets/i18n/ru.json

fix: angle read&set unlocks form saving

---

README.md
package.json
src/app/control-schemes/common/binding-edit/binding-servo/binding-servo-edit.component.html
src/app/control-schemes/common/forms/builders/servo-binding-form-builder.service.ts
src/app/control-schemes/common/forms/types.ts
src/app/store/actions/attached-io-props.actions.ts
src/app/store/app-store-version.ts
src/app/store/effects/tasks-processing/compose-tasks.effect.ts
src/app/store/effects/tasks-processing/pre-run-scheme.effect.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/angle-shift-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/i-task-payload-factory.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/servo-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/set-angle-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/payload-factories/speed-shift-task-payload-factory.service.ts
src/app/store/effects/tasks-processing/task-factory/task-factory.service.ts
src/app/store/hub-facades/hub-motor-position-facade.service.ts
src/app/store/migrations/provide-store-migrations.ts
src/app/store/migrations/v23-store.ts
src/app/store/migrations/v23-to-v24-migration.service.spec.ts
src/app/store/migrations/v23-to-v24-migration.service.ts
src/app/store/migrations/v24-store.ts
src/app/store/models/attached-io-props.model.ts
src/app/store/models/control-scheme.model.ts
src/app/store/reducers/attached-io-props.reducer.ts
src/app/store/selectors/attached-io-props.selectors.ts
src/app/store/selectors/port-tasks.selectors.ts
src/assets/i18n/en.json
src/assets/i18n/ru.json

feat: add option to auto-calibrate servo on scheme startup

---

jest.config.app.ts
modules/features/about/jest.config.ts
modules/features/bluetooth-unavailable/jest.config.ts
modules/features/control-scheme-binding-create/jest.config.ts
modules/features/control-scheme-binding-edit/jest.config.ts
modules/features/control-scheme-port-config-edit/jest.config.ts
modules/features/control-scheme-view/jest.config.ts
modules/features/control-schemes-list/jest.config.ts
modules/features/controller-view/jest.config.ts
modules/features/controllers-list/jest.config.ts
modules/features/hub-edit/jest.config.ts
modules/features/hub-view/jest.config.ts
modules/features/hubs-list/jest.config.ts
modules/features/not-found/jest.config.ts
modules/features/root/jest.config.ts
modules/features/settings/jest.config.ts
modules/shared/control-schemes/jest.config.ts
modules/shared/controller/jest.config.ts
modules/shared/misc/jest.config.ts
modules/shared/ui/jest.config.ts
modules/store/jest.config.ts
modules/store/tsconfig.json

This reverts commit cb32c359a74a23ea3682ff8b7f2de7e8b06f616d.

Revert "chore: disable 'isolatedModules' jest option"

---

modules/shared/controller-profiles/src/lib/gamepad-profile-factory.service.ts
modules/shared/controller-profiles/src/lib/i-controllers-config.ts
modules/store/src/lib/effects/controllers/capture-input/capture-gamepad-input.effect.ts
modules/store/src/lib/effects/controllers/listen-connect/listen-gamepad-connect.effect.ts

* optimize gamepad detection flow

fix: detect gamepads connection with each animation frame

---

modules/store/src/lib/effects/controllers/capture-input/capture-gamepad-input.effect.ts

fix: consider ignore input for gamepad buttons & axes

---

modules/shared/controller-profiles/src/lib/gamepad-value-transform.service.ts
modules/store/src/lib/effects/controllers/capture-input/capture-gamepad-input.effect.ts

* fix activation threshold calculation

fix: apply axial&button trims to input value

---

modules/shared/control-schemes/src/lib/binding-edit/binding-servo/binding-servo-edit.component.ts
package-lock.json
package.json

* fix servo range query results

fix: bump rxpoweredup (mitigate un-interruptable servo tasks)

---

README.md
docs/steam_deck_EN.md

* add ref to steam deck installation manual
* add running scheme screenshot

docs: update README.md

---

modules/bindings/src/lib/common/controls/select-controller/binding-control-select-controller.component.html
modules/bindings/src/lib/set-speed/set-speed-filter.service.ts
modules/bindings/src/lib/set-speed/set-speed-payload-hash.ts

* fix missing Accelerate input action

fix: correct setSpeed task hash calculation (deduplicate tasks)

---

modules/bindings/src/lib/stepper/stepper-binding-form-builder.service.ts
modules/pages/control-scheme-port-config-edit/src/lib/port-config-edit-page.component.ts
modules/pages/control-scheme-view/src/lib/control-scheme-general-info/control-scheme-general-info.component.html
modules/pages/control-scheme-view/src/lib/control-scheme-general-info/control-scheme-general-info.component.ts
modules/pages/control-schemes-list/src/lib/control-scheme-list-page.component.html
modules/pages/controller-view/src/lib/controller-view-page.component.scss
src/assets/i18n/ru.json
src/styles/styles.scss

* increase stepper angle range
* remove warning about unsaved changes after port config saving
* validate control scheme name edit form (scheme name uniqueness)
* remove global button resizing style, use local in control scheme list
* increase space for label in controller view card
* fix missing page title in RU locale for hubs list page

fix: misc fixes

---

modules/bindings/src/lib/binding-validator.service.ts
modules/bindings/src/lib/gearbox/gearbox-control-binding-form-builder.service.ts
modules/bindings/src/lib/i-binding-form-builder.ts
modules/bindings/src/lib/i-form-builder.ts
modules/bindings/src/lib/servo/servo-binding-form-builder.service.ts
modules/bindings/src/lib/set-angle/set-angle-binding-form-builder.service.ts
modules/bindings/src/lib/set-speed/set-speed-binding-form-builder.service.ts
modules/bindings/src/lib/stepper/stepper-binding-form-builder.service.ts
modules/bindings/src/lib/train-control/binding-train-control-edit.component.ts
modules/bindings/src/lib/train-control/train-control-binding-form-builder.service.ts
modules/bindings/src/lib/train-control/train-control-binding-form-mapper.service.ts
modules/bindings/src/lib/train-control/train-control-binding-form.ts
modules/bindings/src/lib/train-control/train-control-l10n.service.ts
modules/bindings/src/lib/train-control/train-control-task-input-extractor.service.ts
modules/bindings/src/lib/train-control/train-control-task-payload-builder.service.ts
modules/store/src/lib/migrations/v29-v30/v29-store.ts
modules/store/src/lib/migrations/v29-v30/v29-to-v30-migration.service.spec.ts
modules/store/src/lib/migrations/v29-v30/v29-to-v30-migration.service.ts
modules/store/src/lib/models/control-scheme.model.ts

* fix Train and Gearbox scheme import bug (improper form patching)

refactor: remove generic input actions usage in Train Control

---

modules/store/src/lib/effects/hub/subscribe-to-button-state-on-connect.ts

fixes error in console after hub is disconnected

fix: do not unsubscribe from hub properties after hub disconnected

---

src/styles/styles.scss
src/styles/theming.scss

fix: proper checkbox color for select options

---

modules/pages/hub-view/src/lib/hub-io-view/hub-io-view.component.html
modules/pages/hub-view/src/lib/hub-io-view/hub-io-view.component.scss
modules/pages/hub-view/src/lib/hub-properties-view/hub-properties-view.component.html
modules/pages/hub-view/src/lib/hub-properties-view/hub-properties-view.component.scss
modules/pages/hub-view/src/lib/hub-view-page.component.html
modules/pages/hub-view/src/lib/hub-view-page.component.ts
modules/pages/hub-view/src/lib/hub-view-page.selectors.ts
modules/shared/ui/src/lib/changelog/changelog.ts
modules/shared/ui/src/lib/io-type-to-l10n-key/io-type-to-l10n-key.service.ts
modules/store/src/lib/actions/hub-runtime-data.actions.ts
modules/store/src/lib/effects/hub/index.ts
modules/store/src/lib/effects/hub/request-hub-firmware-version-on-connect.ts
modules/store/src/lib/effects/hub/request-hub-hardware-version-on-connect.ts
modules/store/src/lib/models/hub-runtime-data.model.ts
modules/store/src/lib/reducers/hub-runtime-data.reducer.ts
modules/store/src/lib/selectors/hub-runtime-data.selectors.ts
package-lock.json
package.json
src/assets/i18n/en.json
src/assets/i18n/ru.json

* multiple fixes of hub view page

feat: display hub hardware & software info

---

modules/bindings/src/lib/common/calc-input-gain.ts
modules/bindings/src/lib/common/controls/select-controller/binding-control-select-controller.component.ts
modules/bindings/src/lib/common/controls/select-input-pipes-preset/input-pipe-preset-to-l10n-key.pipe.ts
modules/bindings/src/lib/common/controls/select-input-pipes-preset/input-pipes-preset.ts
modules/bindings/src/lib/common/controls/select-input-pipes-preset/select-input-pipe-preset.component.ts
modules/bindings/src/lib/common/filter-input-pipe-types-by-input-type.ts
modules/bindings/src/lib/common/input-extractor.service.ts
modules/bindings/src/lib/common/input-pipes/apply-gain-input-pipe.ts
modules/bindings/src/lib/common/input-pipes/on-off-input-pipe.ts
modules/bindings/src/lib/gearbox/gearbox-binding-form-builder.service.ts
modules/bindings/src/lib/servo/servo-binding-edit.component.ts
modules/bindings/src/lib/servo/servo-binding-form-builder.service.ts
modules/bindings/src/lib/set-angle/set-angle-binding-form-builder.service.ts
modules/bindings/src/lib/speed/speed-binding-edit.component.ts
modules/bindings/src/lib/speed/speed-binding-form-builder.service.ts
modules/bindings/src/lib/stepper/stepper-binding-form-builder.service.ts
modules/bindings/src/lib/train/train-binding-form-builder.service.ts
modules/shared/ui/src/lib/changelog/changelog.ts
modules/store/src/lib/migrations/v30-v31/v30-store.ts
modules/store/src/lib/migrations/v30-v31/v30-to-v31-migration.service.spec.ts
modules/store/src/lib/migrations/v30-v31/v30-to-v31-migration.service.ts
modules/store/src/lib/models/control-scheme.model.ts
src/assets/i18n/en.json
src/assets/i18n/ru.json

* remove Linear gain, remove old l10n keys related to input gain
* fix inputPipes form patching

feat: add 'on/off' input pipe

---

modules/store/src/lib/effects/control-scheme/scheme-pre-run/create-widget-read-tasks.ts
modules/store/src/lib/effects/control-scheme/scheme-pre-run/pre-run-scheme.effect.ts

(fixes widgets not updating after scheme start)

fix: remove widgets update sub

---

modules/shared/components/src/lib/info-notification/info-notification.component.html
modules/shared/components/src/lib/info-notification/info-notification.component.ts
modules/store/src/lib/notification-facade.service.ts

+ remove duration from 'app updated' and 'error' notifications

fix(a11y): remove "dismiss" button from timed notifications

---

modules/bindings/src/lib/common/controls/select-controller/binding-control-select-controller.component.html
modules/pages/control-scheme-view/src/lib/bindings-section/hub-port-binding-list-item/hub-port-binding-list-item.component.html
modules/pages/control-scheme-view/src/lib/bindings-section/hub-port-binding-list-item/hub-port-binding-list-item.component.ts
modules/pages/control-scheme-view/src/lib/widgets/reorder-widgets-dialog/reorder-widget-dialog.component.html
modules/shared/misc/src/lib/screen-size-observer.service.ts
modules/store/src/lib/effects/control-scheme/index.ts
modules/store/src/lib/effects/control-scheme/notify-on-control-scheme-started.effect.ts
modules/store/src/lib/effects/control-scheme/notify-on-control-scheme-stopped.effect.ts
src/app/nav-menu/full-nav-menu/full-nav-menu.component.html
src/assets/i18n/en.json
src/assets/i18n/ru.json

+ descriptive text for nav links in cs view
+ descriptive text for reorder widgets buttons
+ fix screenSizeObserver reports
+ add notifications on control scheme start/stop

fix(a11y): address a11y issues
